name: Deploy

on:
  push:
    branches:
      - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: main
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          cache-dependency-path: main/package-lock.json
          node-version: 16
          cache: npm
      - name: Install dependencies
        working-directory: main
        run: npm ci
      - name: Build
        working-directory: main
        run: npm run build
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: gh-pages
          path: gh-pages
      - name: Deploy
        run: |
          ls
          mkdir deploy-copy
          mv gh-pages/* deploy-copy
          # mv main/dist/* gh-pages
          # mv deploy-copy/CNAME gh-pages
          cd gh-pages
          git config --global user.email "github@github.com"
          git config --global user.name "github actions"
          git add .
          git commit -m "Deploy update"
          git push origin gh-pages
